version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/landeed_interview
    depends_on:
      - db

  db:
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_DB: landeed_interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
