// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug)]
pub struct Customer {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct Order {
    pub id: i32,
    pub customer_id: i32,
    pub created_at: i32,
    pub status: String,
    pub premium: bool,
}

#[derive(Queryable, Debug)]
pub struct Payment {
    pub id: i32,
    pub order_id: i32,
    pub created_at: i32,
    pub status: String,
}

